### ISSUE TITLE
Creating multiple sessions at once.

### ISSUE THREAD

**Issue by simon2k** [cs3b/kameleon#23]
Sometimes is good to create multiple sessions at once.. for example when I want to operate on 3 sessions, I have to call

``` ruby
create_session(:admin)
create_session(:customer)
create_session(:client)
```

When simpler is call one method - i.e. #create_sessions with 3 params:

``` ruby
create_sessions(:admin, :customer, :client)
```

And the active session will be the last, which was created (in above example - :client)

**Comment by cs3b** [comment]
duplicates of #24
