### ISSUE TITLE
garbage_collector sometimes crashes tests suite

### ISSUE THREAD

**Issue by ghost** [cs3b/kameleon#31]
Please add to gem description that using your garbage_collector requires greater RAM space (2GB is not enough). This garbage_collector may crash tests suite and cause lots of unnecessary debuging (there is not message pointing the problem).

Instead of

``` ruby
require 'kameleon/ext/rspec/all'
```

it is safer to do

``` ruby
require 'kameleon/ext/rspec/dsl'
require 'kameleon/ext/rspec/headless'
```

**Comment by cs3b** [comment]
@boro-selleo have you encounter this more times?

Not sure, but it might be related to you environment setup
