### ISSUE TITLE
not_see dsl word improvement

### ISSUE THREAD

**Issue by socjopata** [cs3b/kameleon#4]
Hey, I've noticed that not_see is incomplete in comparison to the see method.

 For example I can construct"I can see an image on page", but I cannot construct "I don't see image on page" because not_see method isn't aware of image type.

**Comment by simon2k** [comment]
This has been implemented in:

https://github.com/Skieloch/kameleon/commit/1f4b08be4104218f09923851acf837515c32fb6a
